### ISSUE TITLE
Fix serving of static files in Django

### ISSUE THREAD

**Issue by nicasion** [17356-final-project-org/17776-final-project#18]
right now, css isn't loading because of this

**Comment by cggonzal** [comment]
I put this on the backlog for next week. Should not be a big deal to implement.

**Comment by cggonzal** [comment]
@nicasion this should work now. I can't test it locally though so we'll have to push to azure and see if it's working now.

**Comment by nicasion** [comment]
pushed to azure, but the css does not show up yet

i suspect that there needs to be some changes to the config for Github Actions

**Comment by nicasion** [comment]
Output of Github Actions:

Running collectstatic...

161 static files copied to '/github/workspace/backend/static'.
'collectstatic' exited with exit code .
Done in 1 sec(s).

**Comment by nicasion** [comment]
this might be helpful: https://azure.github.io/AppService/2020/12/11/cicd-for-python-apps.html

**Comment by cggonzal** [comment]
alright I'll take a look

**Comment by cggonzal** [comment]
as discussed in the meeting, the site works fine so this is not worth looking into.
