### ISSUE TITLE
Change keyword matching to be case insensitive

### ISSUE THREAD

**Issue by nicasion** [17356-final-project-org/17776-final-project#43]
currently, keyword match is case sensitive so 
eg. HP V24i FHD Monitor | 23.8-inch Diagonal Full HD Computer Monitor with IPS Panel and 3-Sided Micro Edge Design | Low Blue Light Screen with HDMI and VGA Ports | (9RV15AA#ABA)
-> gives no result

but changing to lower caps "hp" "computer" "monitor"

hp V24i FHD monitor | 23.8-inch Diagonal Full HD computer Monitor with IPS Panel and 3-Sided Micro Edge Design | Low Blue Light Screen with HDMI and VGA Ports | (9RV15AA#ABA)
-> yields result

**Comment by cggonzal** [comment]
yeah this should be an easy fix. I'm sure @diegomtzg can do this relatively quickly
